### ISSUE TITLE
running test.sh

### ISSUE THREAD

**Issue by farrell236** [luukboulogne/stoic2021-baseline#1]
Hi Luuk,

I'm trying to run the baseline example, but it doesn't seem to be completing successfully... The docker build process completes fine, but when running `sudo ./test.sh` I get the following error:

```
...
build debug logs here
...
Successfully built 45e1fdb80f76
Successfully tagged stoicalgorithm:latest
stoicalgorithm-output
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Could not load 1.0.000.000000.0.00.0.0000000000.0000.0000000000.000.zraw using <evalutils.io.SimpleITKLoader object at 0x7fd003f33a90>.
0.5522074103355408
0.5823957324028015
Expected output was not found...
stoicalgorithm-output
farrell@skylab:~/stoic2021-baseline$ 
```

Thanks!

**Comment by luukboulogne** [comment]
Hi Farrell,

Thank you for reporting this issue. The "Expected output was not found..." error occurs because at the 8th decimal place, the output of the container differs from the expected severe covid output (see [expected_output-probability-severe-covid-19.json](https://github.com/luukboulogne/stoic2021-baseline/blob/40cb3f59567819e93359e9711e31fff9c103540b/test/expected_output-probability-severe-covid-19.json#L1)). I do not know yet why this occurs, but it is only a very small difference and it would not be notable on the Leaderboard.

**Comment by farrell236** [comment]
Ohhhh, test script is testing to see if the docker container is built correctly (not actually testing the model), hence comparing the floating point precision(?)

**Comment by luukboulogne** [comment]
You can indeed use it to check if it builds the container correctly. Additionally, you could use it to check if the output of your container is correct for some image. But seemingly this comparison can fail due to tiny floating point differences.

**Comment by farrell236** [comment]
Thanks Luuk!
